import type { IconName } from '@/components/atoms/EmpireIcon'

export type EducationDoc = {
  id: string
  title: string
  category: string
  icon: IconName
  summary: string
  path: string
  learn: string[]
  tags: string[]
}

export const EDUCATION_DOCS: EducationDoc[] = [
  {
    id: 'overview',
    title: 'Empire Overview',
    category: 'Core',
    icon: 'overview',
    path: '/',
    summary: 'The executive surface for health, payroll, pipeline, standings, notifications, and unit launch.',
    learn: ['Read headcount, payroll, active deals, and pipeline value.', 'Use Territory Health to find weak units first.', 'Open The Standings to compare people or units by quarter.'],
    tags: ['dashboard', 'health', 'standings', 'notifications'],
  },
  {
    id: 'network',
    title: 'Company Network',
    category: 'Core',
    icon: 'sitemap',
    path: '/?tab=network',
    summary: 'A navigable company graph that connects the company node to units, members, and documents.',
    learn: ['Drag the canvas to pan across dense areas.', 'Use zoom in, zoom out, and center controls to inspect structure.', 'Open unit nodes to jump into the domain workspace.'],
    tags: ['network', 'graph', 'mcp', 'documents'],
  },
  {
    id: 'roster',
    title: 'Roster',
    category: 'Core',
    icon: 'people',
    path: '/?tab=roster',
    summary: 'Every member grouped by unit with dossier access for role, cost, country, rank, and XP context.',
    learn: ['Open a person card for the full dossier.', 'Compare role, contract type, and unit ownership.', 'Use rank and XP data to understand contribution history.'],
    tags: ['people', 'members', 'dossier', 'roles'],
  },
  {
    id: 'deals',
    title: 'Deals',
    category: 'Revenue',
    icon: 'handshake',
    path: '/?tab=deals',
    summary: 'Pipeline management with deal value, status, commission, and unit linkage.',
    learn: ['Create and edit pipeline deals.', 'Link revenue to the owning unit.', 'Use status and commission fields to keep finance and partnerships aligned.'],
    tags: ['sales', 'pipeline', 'commission', 'revenue'],
  },
  {
    id: 'approvals',
    title: 'Approvals',
    category: 'Governance',
    icon: 'scales',
    path: '/approvals',
    summary: 'Decision queue for budget, legal, hiring, vendor, and operating requests.',
    learn: ['Raise requests with category and priority.', 'Approve, reject, or escalate decisions.', 'Keep high-priority work visible before it becomes operational drag.'],
    tags: ['governance', 'requests', 'decisions', 'risk'],
  },
  {
    id: 'unit-workspace',
    title: 'Unit Workspace',
    category: 'Domains',
    icon: 'shield',
    path: '/departments/operations',
    summary: 'Each unit acts like a domain: clear ownership, KPIs, follow-ups, tickets, contracts, and specialist tools.',
    learn: ['Use Overview for unit health and roster.', 'Use KPIs, follow-ups, tickets, and contracts as the operational spine.', 'Treat each unit as a domain with explicit inputs, outputs, and accountability.'],
    tags: ['domains', 'units', 'kpis', 'ownership'],
  },
  {
    id: 'structure',
    title: 'Structure',
    category: 'Domains',
    icon: 'sitemap',
    path: '/departments/operations?tab=structure',
    summary: 'Reporting structure and role mapping for a unit.',
    learn: ['Inspect hierarchy and manager relationships.', 'Open role details for reporting changes.', 'Use structure to reduce ambiguity before scaling a team.'],
    tags: ['org chart', 'hierarchy', 'roles', 'reporting'],
  },
  {
    id: 'tickets',
    title: 'Tickets',
    category: 'Execution',
    icon: 'rocket',
    path: '/departments/engineering?tab=tickets',
    summary: 'Sprint and work tracking for unit execution.',
    learn: ['Create tickets with priority, owner, and status.', 'Attach files and comments to keep context local.', 'Use sprint scope and burndown to see delivery pressure.'],
    tags: ['execution', 'sprints', 'work', 'delivery'],
  },
  {
    id: 'contracts',
    title: 'Contracts',
    category: 'Governance',
    icon: 'document',
    path: '/departments/legal?tab=contracts',
    summary: 'Contract workflow for people, vendors, and cross-unit legal routing.',
    learn: ['Create contracts from prefilled unit context.', 'Track expiry, files, and version history.', 'Route legal-heavy work into the right review lane.'],
    tags: ['contracts', 'legal', 'documents', 'vendors'],
  },
  {
    id: 'finance',
    title: 'Finance',
    category: 'Specialist Units',
    icon: 'finance',
    path: '/departments/finance',
    summary: 'Finance operations for spend, invoices, journal entries, accounts, and payroll awareness.',
    learn: ['Track spend and receipt evidence.', 'Generate invoices and account entries.', 'Use finance as the truth layer for company cost.'],
    tags: ['finance', 'invoices', 'spend', 'accounting'],
  },
  {
    id: 'engineering',
    title: 'Engineering',
    category: 'Specialist Units',
    icon: 'engineering',
    path: '/departments/engineering',
    summary: 'Service, delivery, and technical ownership workspace.',
    learn: ['Track services and technical work.', 'Connect tickets to implementation progress.', 'Keep ownership clear as services split into domains.'],
    tags: ['engineering', 'services', 'architecture', 'delivery'],
  },
  {
    id: 'legal',
    title: 'Legal',
    category: 'Specialist Units',
    icon: 'legal',
    path: '/departments/legal',
    summary: 'Templates, generated documents, signatures, and compliance review.',
    learn: ['Create templates and generated legal documents.', 'Review and sign where required.', 'Keep contract state connected to operational work.'],
    tags: ['legal', 'templates', 'signatures', 'compliance'],
  },
  {
    id: 'operations',
    title: 'Operations',
    category: 'Specialist Units',
    icon: 'operations',
    path: '/departments/operations',
    summary: 'Vendor, process, and operating cadence control.',
    learn: ['Manage vendors and process ownership.', 'Surface stale processes before they break cadence.', 'Use operations as the connective tissue across units.'],
    tags: ['operations', 'vendors', 'process', 'cadence'],
  },
  {
    id: 'mcp',
    title: 'MCP Console',
    category: 'Platform',
    icon: 'link',
    path: '/mcp',
    summary: 'Tool and account access surface for controlled agent operations.',
    learn: ['Inspect available tool connections.', 'Keep account-level permissions aligned with the current user role.', 'Use MCP context to support controlled production actions.'],
    tags: ['mcp', 'tools', 'permissions', 'accounts'],
  },
  {
    id: 'settings',
    title: 'Settings',
    category: 'Platform',
    icon: 'cog',
    path: '/settings',
    summary: 'Application configuration for profile, theme, and system preferences.',
    learn: ['Adjust local experience without changing domain data.', 'Use theme settings for operator comfort.', 'Keep admin-only behavior in governed surfaces.'],
    tags: ['settings', 'profile', 'theme', 'configuration'],
  },
  {
    id: 'admin',
    title: 'Admin & IAM',
    category: 'Platform',
    icon: 'lock',
    path: '/admin',
    summary: 'Administrative access and role-sensitive controls.',
    learn: ['Review privileged users and roles.', 'Keep access changes auditable.', 'Separate everyday operator work from admin authority.'],
    tags: ['admin', 'iam', 'roles', 'security'],
  },
]

