import type { IconName } from '@/components/atoms/EmpireIcon'

export type EducationDoc = {
  id: string
  title: string
  category: string
  icon: IconName
  summary: string
  path: string
  steps: string[]
  outcome: string
  tags: string[]
}

export const EDUCATION_DOCS: EducationDoc[] = [
  {
    id: 'overview',
    title: 'Run the Executive Overview',
    category: 'Core',
    icon: 'overview',
    path: '/',
    summary: 'Daily command surface for company health, payroll, pipeline, standings, and alerts.',
    steps: [
      'Start with the four top metrics: headcount, monthly payroll, active deals, and pipeline value.',
      'Open Territory Health and inspect units outside the healthy band before reading any detail pages.',
      'Use The Standings quarter selector to compare people or units for the active operating period.',
      'Review Notifications for live risks and click through only when an alert needs action.',
      'Use the Units launcher when you know which domain owns the work.',
      'End the pass by opening Approvals if any decision count is shown in the header.',
    ],
    outcome: 'You know where the company is healthy, where it is weak, and what needs a decision today.',
    tags: ['dashboard', 'health', 'standings', 'notifications', 'daily review'],
  },
  {
    id: 'network',
    title: 'Navigate the Company Network',
    category: 'Core',
    icon: 'sitemap',
    path: '/?tab=network',
    summary: 'Interactive graph for units, members, documents, and context that MCP agents can reason over.',
    steps: [
      'Open Network from the top tabs on the overview page.',
      'Drag on empty canvas space to pan across the graph.',
      'Use plus and minus controls to zoom until labels and edges are readable.',
      'Use the center control whenever you lose the company node.',
      'Hover nodes to read the context tip before clicking.',
      'Click a unit node to enter that unit workspace with the same domain context.',
    ],
    outcome: 'You can move through the organization as a context map instead of hunting through menus.',
    tags: ['network', 'graph', 'zoom', 'pan', 'mcp'],
  },
  {
    id: 'roster',
    title: 'Inspect the Roster',
    category: 'Core',
    icon: 'people',
    path: '/?tab=roster',
    summary: 'People directory grouped by unit with dossiers for role, cost, location, rank, and XP.',
    steps: [
      'Open Roster from the overview tabs.',
      'Scan by unit heading first, then by person card.',
      'Click a person to open the dossier.',
      'Check contract type, department, role, country, rank, and XP context.',
      'Use the dossier to understand capacity before changing tickets, contracts, or unit ownership.',
    ],
    outcome: 'You understand who owns work, what they cost, and where they sit in the operating model.',
    tags: ['people', 'members', 'dossier', 'capacity'],
  },
  {
    id: 'deals',
    title: 'Manage Deals',
    category: 'Revenue',
    icon: 'handshake',
    path: '/?tab=deals',
    summary: 'Pipeline workflow for deal value, client, status, commission, and linked owning unit.',
    steps: [
      'Open Deals from the overview tabs.',
      'Create a deal with title, client, amount, currency, and status.',
      'Link the deal to the unit that owns delivery or revenue accountability.',
      'Update status as the deal moves from prospect to negotiation to closed state.',
      'Open deal details before changing commission assumptions.',
      'Use pipeline totals on Overview to confirm revenue impact after edits.',
    ],
    outcome: 'Revenue work is tied to the responsible domain and visible in executive metrics.',
    tags: ['sales', 'pipeline', 'commission', 'revenue'],
  },
  {
    id: 'approvals',
    title: 'Work the Approval Queue',
    category: 'Governance',
    icon: 'scales',
    path: '/approvals',
    summary: 'Decision queue for budget, legal, hiring, vendor, and operating requests.',
    steps: [
      'Open Approvals from the dock or the header decision alert.',
      'Filter mentally by priority: critical and high requests first.',
      'Open the request and read source unit, target unit, category, and rationale.',
      'Approve only when ownership, budget, and next action are clear.',
      'Reject when the request lacks evidence or violates operating constraints.',
      'Escalate or leave pending only when a missing fact must be resolved.',
    ],
    outcome: 'Decisions move quickly without hiding accountability or risk.',
    tags: ['governance', 'requests', 'decisions', 'risk'],
  },
  {
    id: 'unit-workspace',
    title: 'Operate a Unit Workspace',
    category: 'Domains',
    icon: 'shield',
    path: '/departments/operations',
    summary: 'Every unit behaves as a domain with health, roster, structure, KPIs, follow-ups, tickets, and contracts.',
    steps: [
      'Open a unit from the dock, network graph, territory health, or direct link.',
      'Start on Overview and read health score, team size, monthly cost, and open follow-ups.',
      'Check the roster to confirm who owns work inside the unit.',
      'Open Structure when reporting lines or role ownership are unclear.',
      'Use KPIs to judge performance before creating new work.',
      'Use Follow-ups, Tickets, and Contracts for execution rather than keeping action items in notes.',
    ],
    outcome: 'Each unit has clear ownership, measurable health, and an execution path.',
    tags: ['domains', 'units', 'kpis', 'ownership'],
  },
  {
    id: 'structure',
    title: 'Edit Reporting Structure',
    category: 'Domains',
    icon: 'sitemap',
    path: '/departments/operations?tab=structure',
    summary: 'Interactive org tree for reporting lines and structured role linkage.',
    steps: [
      'Open a unit and select the Structure tab.',
      'Drag the canvas if the tree is wider than the viewport.',
      'Zoom in or out until the reporting lines are readable.',
      'Click center to reset the tree when you lose context.',
      'Click a person card to open role and reporting settings.',
      'Pick the structured role and reports-to relationship, then save.',
    ],
    outcome: 'The unit hierarchy is readable, editable, and safe from hidden reporting loops.',
    tags: ['org chart', 'hierarchy', 'roles', 'reporting'],
  },
  {
    id: 'tickets',
    title: 'Run Unit Tickets',
    category: 'Execution',
    icon: 'rocket',
    path: '/departments/engineering?tab=tickets',
    summary: 'Execution workflow for backlog, sprint scope, owners, attachments, comments, and delivery status.',
    steps: [
      'Open the unit that owns the work and select Tickets.',
      'Create a ticket with type, status, priority, assignee, reporter, and sprint when relevant.',
      'Use comments for decision trail and attach files when work needs evidence.',
      'Move status through backlog, to do, in progress, review, and done.',
      'Open sprint controls to manage delivery windows and scope.',
      'Use burndown and scope metrics to see whether the unit is overcommitted.',
    ],
    outcome: 'Work is tracked in the owning unit with enough context for review and delivery.',
    tags: ['execution', 'sprints', 'work', 'delivery'],
  },
  {
    id: 'contracts',
    title: 'Create and Review Contracts',
    category: 'Governance',
    icon: 'document',
    path: '/departments/legal?tab=contracts',
    summary: 'Contract workflow for employees, companies, partners, files, expiry, routing, and version history.',
    steps: [
      'Open Contracts from the owning unit or Legal.',
      'Create a contract with type, status, counterparty, owner, and effective dates.',
      'Attach or link the contract document when available.',
      'Use lifecycle status to move draft, review, approval, signed, active, or archived.',
      'Check expiry signals and version history before making edits.',
      'Route legal-heavy contracts to the Legal workflow instead of resolving inside the wrong unit.',
    ],
    outcome: 'Contracts stay tied to operational ownership while preserving legal review and version control.',
    tags: ['contracts', 'legal', 'documents', 'vendors'],
  },
  {
    id: 'finance',
    title: 'Run Finance',
    category: 'Specialist Units',
    icon: 'finance',
    path: '/departments/finance',
    summary: 'Finance workspace for spend, invoices, statements, journals, accounts, and payroll awareness.',
    steps: [
      'Open Finance from Units or direct navigation.',
      'Review finance KPIs and statements before entering new data.',
      'Log spend with amount, category, payment method, and receipt evidence.',
      'Generate invoices from the invoice tool and verify preview before export.',
      'Use journal entries only when debits and credits balance.',
      'Export statements or ledger CSV when finance needs outside review.',
    ],
    outcome: 'Company money has traceable evidence, balanced accounting, and exportable reporting.',
    tags: ['finance', 'invoices', 'spend', 'accounting'],
  },
  {
    id: 'engineering',
    title: 'Run Engineering',
    category: 'Specialist Units',
    icon: 'engineering',
    path: '/departments/engineering',
    summary: 'Technical ownership workspace for services, deployments, incidents, dependencies, and delivery tickets.',
    steps: [
      'Open Engineering and read service health before creating new work.',
      'Use service records to map ownership and tier.',
      'Log deployments with service, version, status, author, and commit time.',
      'Record incidents with severity and cause so reliability data is not lost.',
      'Use dependencies to understand blast radius before changing a service.',
      'Move execution work into Tickets so delivery is visible outside engineering.',
    ],
    outcome: 'Technical systems are connected to ownership, deployment history, and delivery work.',
    tags: ['engineering', 'services', 'architecture', 'delivery'],
  },
  {
    id: 'legal',
    title: 'Run Legal',
    category: 'Specialist Units',
    icon: 'legal',
    path: '/departments/legal',
    summary: 'Legal workspace for templates, generated documents, review, signatures, and compliance routing.',
    steps: [
      'Open Legal and start with templates when creating repeatable documents.',
      'Generate the document from a template and fill required parameters.',
      'Review pricing, rendered text, and counterparty details before status changes.',
      'Use print or markdown export when outside counsel or a client needs a copy.',
      'Capture signatures inside the document workflow where possible.',
      'Route contracts back to the operational unit once legal review is complete.',
    ],
    outcome: 'Legal work is repeatable, reviewable, and connected to the business workflow it supports.',
    tags: ['legal', 'templates', 'signatures', 'compliance'],
  },
  {
    id: 'marketing',
    title: 'Run Marketing',
    category: 'Specialist Units',
    icon: 'marketing',
    path: '/departments/marketing',
    summary: 'Growth workspace for campaigns, channels, leads, influencers, social connections, CAC, ROAS, and conversion.',
    steps: [
      'Open Marketing and read blended CAC, ROAS, spend, leads, and conversion metrics.',
      'Create campaigns with channel, budget, spend, leads, conversions, and revenue.',
      'Move leads through stages and watch stage conversion percentages.',
      'Use influencer and social-account views for acquisition sources outside paid campaigns.',
      'Sync supported channels when credentials are connected.',
      'Use performance data before scaling spend.',
    ],
    outcome: 'Growth decisions are tied to spend, conversion, and revenue evidence.',
    tags: ['marketing', 'campaigns', 'leads', 'growth'],
  },
  {
    id: 'operations',
    title: 'Run Operations',
    category: 'Specialist Units',
    icon: 'operations',
    path: '/departments/operations',
    summary: 'Operating workspace for vendors, processes, automation, stale reviews, criticality, and SLA health.',
    steps: [
      'Open Operations and scan vendor and process KPIs first.',
      'Create vendors with category, criticality, owner, spend, and status.',
      'Review process rows for owner, area, automation percentage, and stale indicator.',
      'Create or update processes when work is undocumented or outdated.',
      'Prioritize critical vendors and stale high-impact processes before low-risk cleanup.',
      'Use Operations as the escalation point for cross-unit execution friction.',
    ],
    outcome: 'The company operating system stays documented, owned, and reviewable.',
    tags: ['operations', 'vendors', 'process', 'cadence'],
  },
  {
    id: 'mcp',
    title: 'Use the MCP Console',
    category: 'Platform',
    icon: 'link',
    path: '/mcp',
    summary: 'Controlled tool/account surface for wizard keys, recurring questions, reports, and role-aware agent operations.',
    steps: [
      'Open MCP from the dock.',
      'Generate a wizard key only for the tool and account context you intend to use.',
      'Configure recurring questions when an operating ritual should repeat weekly.',
      'Generate reports to collect completed tickets and processed documents.',
      'Keep account permissions aligned with the logged-in role.',
      'Do not use MCP as a bypass for admin or production permissions.',
    ],
    outcome: 'Agent tooling stays controlled, auditable, and aligned with user authority.',
    tags: ['mcp', 'tools', 'permissions', 'accounts'],
  },
  {
    id: 'settings',
    title: 'Configure Settings',
    category: 'Platform',
    icon: 'cog',
    path: '/settings',
    summary: 'Operator preferences and system configuration for profile, theme, and local experience.',
    steps: [
      'Open Settings from the dock.',
      'Review profile and theme options before changing operational data elsewhere.',
      'Switch theme based on working conditions, not as a data change.',
      'Keep preference changes separate from unit workflow decisions.',
      'Return to the dock to continue operational work.',
    ],
    outcome: 'Operators can tune the interface without disturbing business data.',
    tags: ['settings', 'profile', 'theme', 'configuration'],
  },
  {
    id: 'admin',
    title: 'Admin and IAM',
    category: 'Platform',
    icon: 'lock',
    path: '/admin',
    summary: 'Privileged role and rank management for users who are allowed to administer access.',
    steps: [
      'Open Admin only when your role grants admin or IAM permissions.',
      'Find the user whose access needs review.',
      'Assign role and rank deliberately; do not use admin as a convenience shortcut.',
      'Confirm the user still has only the permissions needed for their work.',
      'Use the normal unit workspace for non-access changes.',
    ],
    outcome: 'Access stays explicit, auditable, and separated from everyday operator workflows.',
    tags: ['admin', 'iam', 'roles', 'security'],
  },
  {
    id: 'run-hr',
    title: 'Run People Operations',
    category: 'Specialist Units',
    icon: 'people',
    path: '/departments/hr',
    summary: 'Headcount, hiring funnel, lifecycle events, reviews and attrition — the people engine of the company.',
    steps: [
      'Open People Operations and read the Overview: headcount, open reqs, time-to-fill, attrition.',
      'Use the People tab → People Ops to log lifecycle events (onboarding, promotion, transfer, performance).',
      'Track candidates in Hiring; advance stages as interviews complete.',
      'Run review cycles in Reviews and watch the promo rate.',
      'Create employment contracts from the roster — they file into the Contracts tab.',
    ],
    outcome: 'Every hire, promotion and exit is recorded once, with XP and contracts attached to the right person.',
    tags: ['hr', 'people', 'hiring', 'lifecycle', 'reviews', 'attrition'],
  },
  {
    id: 'run-payroll',
    title: 'Run a Payroll Cycle',
    category: 'Specialist Units',
    icon: 'coins',
    path: '/departments/hr',
    summary: 'Dual-authorized payroll runs: preparation, HR + Finance sign-off, execution on the agreed date, reconciliation.',
    steps: [
      'Open People Operations → Payroll and read the KPIs: next agreed payout date and pending signatures.',
      'Create a run for the period — totals and headcount are computed from the live roster (salary × FTE), and the payout date agreed with Finance is set on the run.',
      'Verify joiners, leavers and salary changes during preparation, then submit the run for authorization.',
      'Collect BOTH signatures: only HR and Finance can authorize, each signing their own side. One signature never releases money.',
      'Execute the payout — allowed only once the run is fully authorized AND the agreed date has arrived. Changing the date resets both signatures.',
      'Reconcile after execution: match bank statements against the run to close the audit trail.',
    ],
    outcome: 'Money only moves with HR and Finance both on record, on the date Finance agreed — with a full audit trail per run.',
    tags: ['payroll', 'hr', 'finance', 'dual authorization', 'agreed date', 'reconciliation', 'salary'],
  },
  {
    id: 'run-creative',
    title: 'Run the Studio',
    category: 'Specialist Units',
    icon: 'pen-nib',
    path: '/departments/creative',
    summary: 'Creative pipeline, assets by kind, and review rounds — connected to unit tickets.',
    steps: [
      'Open Creative and switch to the Studio tab.',
      'Track work through the pipeline stages; link items to tickets so execution stays visible.',
      'File assets by kind (brand, web, video, print) as they ship.',
      'Run review rounds and record approval status per asset.',
      'Feed data manually or via MCP — the same tools agents use.',
    ],
    outcome: 'Creative output is measurable: pipeline, assets and reviews live next to the tickets that drive them.',
    tags: ['creative', 'studio', 'assets', 'pipeline', 'reviews', 'tickets'],
  },
  {
    id: 'run-client-success',
    title: 'Run Client Success',
    category: 'Specialist Units',
    icon: 'handshake',
    path: '/departments/client-success',
    summary: 'Account health, CSAT, onboarding time and expansion revenue across every client.',
    steps: [
      'Open Client Success → Accounts to see the account list and health ratings.',
      'Investigate any account not rated healthy; log interactions and follow-ups.',
      'Track onboarding time for new clients against the unit KPI.',
      'Record expansion (upsell) revenue when accounts grow.',
      'Escalate at-risk accounts via Follow-ups with a cross-reference to the owning unit.',
    ],
    outcome: 'Churn risk is visible early and every account has a current health status and owner.',
    tags: ['client-success', 'accounts', 'csat', 'health', 'expansion'],
  },
  {
    id: 'run-partnerships',
    title: 'Run Partnerships',
    category: 'Specialist Units',
    icon: 'handshake',
    path: '/departments/partnerships',
    summary: 'The channel: deal pipeline, closed deals, pipeline value and deal cycle.',
    steps: [
      'Open Partnerships → Channel to see the live deal pipeline.',
      'Add deals with value and stage; advance them as conversations progress.',
      'Assign a commission owner from the roster — their profile rate drives the auto-calculated commission.',
      'Watch avg deal cycle; stalled deals get a follow-up.',
      'Close deals to feed pipeline KPIs and finance forecasts.',
    ],
    outcome: 'The pipeline is real: every deal has a stage, value, owner and an honest close probability.',
    tags: ['partnerships', 'deals', 'pipeline', 'commission', 'channel'],
  },
  {
    id: 'run-advisory',
    title: 'Run the Council',
    category: 'Specialist Units',
    icon: 'compass',
    path: '/departments/advisory',
    summary: 'Advisory board: advisors, equity/fee terms, and governance guidance.',
    steps: [
      'Open Advisory → Council to see the advisor roster.',
      'Record each advisor’s terms — percentage and the resulting payment amount are shown side by side.',
      'Log advisory sessions as interactions with outcomes.',
      'Route formal recommendations through Approvals when they change policy.',
      'Review advisor contracts in the Contracts tab.',
    ],
    outcome: 'Advisor terms and contributions are explicit — no handshake deals living in someone’s head.',
    tags: ['advisory', 'council', 'advisors', 'equity', 'governance'],
  },
]
