/**
 * Central metric explanations (backlog A17): every KpiCard looks up its label
 * here when no explicit `info` prop is given, so each metric carries an info
 * tooltip explaining what it measures. An explicit `info` prop always wins —
 * use it when a panel needs context-specific wording.
 */
export const METRIC_INFO: Record<string, string> = {
  'A = L + E': 'Accounting identity check: Assets must equal Liabilities plus Equity. A mismatch means unbalanced journal entries.',
  'ARR in Pipeline': 'Annual recurring revenue represented by deals currently in the sales pipeline (not yet closed).',
  'Account Headroom': 'Estimated additional revenue available inside existing accounts before they are fully penetrated.',
  'Accounts Payable': 'Money the company owes suppliers and vendors for goods or services already received.',
  'Accounts Receivable': 'Money owed to the company by clients for delivered work that has been invoiced but not yet paid.',
  'Accounts analysed': 'Number of client accounts included in this health analysis.',
  Accounts: 'Total client accounts tracked in this view.',
  'Active Advisors': 'Advisors currently engaged under an active agreement.',
  'Active Headcount': 'Employees currently on payroll, excluding exits and pending hires.',
  'Active Partners': 'Partner organizations with a live, signed partnership.',
  'Active Services': 'Services currently deployed and serving traffic.',
  'Active Templates': 'Reusable templates currently enabled for use.',
  'Aggregate Balance': 'Combined balance across all linked financial accounts.',
  'Annual Contract Value': 'Average yearly value of a signed customer contract (total contract value normalized to 12 months).',
  'Approval Rate': 'Share of submitted requests that were approved.',
  'At-Risk Accounts': 'Accounts whose health score or activity signals a churn risk — prioritize outreach here.',
  'Attributed Revenue': 'Revenue traced back to this channel or campaign via attribution.',
  'Attrition (12mo)': 'Share of employees who left over the trailing 12 months.',
  'Avg Automation': 'Average share of each process that runs without manual steps.',
  'Avg CSAT': 'Average customer satisfaction score across responses in the period.',
  'Avg Engagement': 'Average interactions (likes, comments, shares) per post relative to reach.',
  'Avg Health': 'Average account health score across the portfolio (0–100).',
  'Avg Response': 'Average time to first response on inbound tickets or requests.',
  'Avg Review': 'Average review rating across deliverables in the period.',
  'Avg Tenure': 'Average length of employment across current staff.',
  'Avg Turnaround': 'Average time from request received to work delivered.',
  'Avg Velocity': 'Average story points (or tickets) completed per sprint.',
  'Avg level': 'Average XP level across people in this view.',
  Backlog: 'Work items accepted but not yet started.',
  'Base Cost / mo': 'Fixed monthly cost to run this service before usage-based charges.',
  'Blended CAC': 'Average cost to acquire one customer across all channels (total spend ÷ new customers).',
  'Blended ROAS': 'Return on ad spend across all channels: attributed revenue ÷ total ad spend.',
  'Board KPIs': 'Key performance indicators tracked at board level.',
  'Board On-Target': 'Share of board-level KPIs currently meeting their target.',
  CSAT: 'Customer satisfaction score from post-interaction surveys.',
  'CapEx : OpEx': 'Ratio of capital expenditure to operating expenditure — how much spend builds assets vs. runs the business.',
  'CapEx Share': 'Capital expenditure as a share of total spend.',
  'Cash Balance': 'Cash currently available across company bank accounts.',
  'Cash Runway': 'Months the company can operate at the current net burn before cash runs out.',
  'Change Requests': 'Client-requested revisions currently open against deliverables.',
  'Channel Win Rate': 'Share of partner-channel deals that closed won.',
  'Client Price / mo': 'Monthly price charged to the client for this service.',
  'Co-Sell Pipeline': 'Pipeline value of deals worked jointly with partners.',
  'Combined Reach': 'Total audience reached across all connected platforms.',
  'Committed Hrs/mo': 'Advisor hours contractually committed per month.',
  'Committed Spend': 'Budget already committed via signed orders and contracts.',
  'Connected (live)': 'Integrations currently connected and syncing data.',
  Connected: 'Accounts or platforms currently connected.',
  Converted: 'Items that reached the converted stage (e.g. intros that became engagements).',
  'Corporate Income Tax': 'Estimated corporate income tax owed on taxable profit for the period.',
  'Cost / Lead': 'Average marketing spend required to generate one lead.',
  'DORA Band': 'Engineering delivery performance band (Elite/High/Medium/Low) from the four DORA metrics.',
  'Deductible Expenses': 'Expenses that reduce taxable profit under current tax rules.',
  'Deploys (30d)': 'Production deployments shipped in the last 30 days.',
  Documents: 'Documents stored in this section.',
  Drafts: 'Items saved as drafts, not yet submitted or published.',
  'Eng Delivery Capacity': 'Engineering capacity available for delivery work this period.',
  'Engagement Rate': 'Interactions as a percentage of impressions or followers.',
  'Equity Granted': 'Total advisor equity granted, with the vested share shown below.',
  'Exits (total)': 'Total employees who have left the company.',
  Financing: 'Net cash flow from financing activities (funding rounds, loans, repayments).',
  Followers: 'Current follower count on this platform.',
  'Gross Margin': 'Revenue minus cost of delivery, as a percentage of revenue.',
  'Gross Profit': 'Revenue minus direct cost of delivering the work.',
  'Gross Retention': 'Share of recurring revenue retained from existing customers, ignoring expansion.',
  Headcount: 'Total people currently employed.',
  'High priority': 'Open items flagged high priority.',
  'High-Risk ARR': 'Annual recurring revenue sitting in at-risk accounts.',
  Impressions: 'Total times content was displayed, regardless of clicks.',
  Improving: 'Accounts or metrics trending upward versus the previous period.',
  Influencers: 'Influencers tracked in the roster.',
  'Intro Conversion': 'Share of warm intros that converted into engagements.',
  Investing: 'Net cash flow from investing activities (asset purchases and sales).',
  'Journal Entries': 'Accounting journal entries recorded in the period.',
  'KR Hit-Rate': 'Share of key results that met their target.',
  'Lead Time': 'Time from work started (commit) to running in production — a core DORA metric.',
  'Lifecycle events': 'Tracked employee lifecycle events (hires, promotions, exits, reviews).',
  'Linked Accounts': 'External accounts linked to this entity.',
  'Logged Spend': 'Spend entries recorded against this budget.',
  'MRR Growth': 'Month-over-month change in monthly recurring revenue.',
  MRR: 'Monthly recurring revenue from active subscriptions and retainers.',
  'MTD Revenue': 'Revenue recognized month-to-date.',
  Made: 'Warm intros made in the period.',
  'Manual / Page': 'Process manuals documented per page or unit.',
  'Margin / mo': 'Monthly profit on this service: client price minus run cost.',
  'Meeting Target': 'Share of tracked items currently meeting their target.',
  Members: 'People in this group or council.',
  'Monthly Burn': 'Total cash spent per month before revenue.',
  'Monthly Run Cost': 'Total infrastructure and tooling cost to run services each month.',
  'Net Burn / mo': 'Cash out minus cash in per month — how fast runway is consumed.',
  'Net Cash Flow': 'Total cash in minus cash out for the period.',
  'Net Income MTD': 'Profit after all expenses, month-to-date.',
  'Net Income': 'Profit after all expenses and taxes.',
  'Net Margin': 'Net income as a percentage of revenue.',
  'Net Revenue Retention': 'Recurring revenue retained from existing customers including expansion — above 100% means growth without new logos.',
  'Net Working Capital': 'Current assets minus current liabilities — short-term financial cushion.',
  'OKR Attainment': 'Average completion across all objectives and key results.',
  Objectives: 'Objectives currently tracked.',
  'Offer Accept': 'Share of extended offers that candidates accepted.',
  'On Target': 'Items currently on track to hit their goal.',
  'On-Time Rate': 'Share of deliverables completed by their due date.',
  'Open Incidents': 'Unresolved incidents currently open.',
  'Open Reqs': 'Open hiring requisitions actively being recruited.',
  'Operating Income': 'Profit from core operations, before interest and taxes.',
  Operating: 'Net cash flow from core business operations.',
  'Overdue AR (90d+)': 'Receivables unpaid for more than 90 days — escalate collection.',
  'Partner-Sourced ARR': 'Annual recurring revenue originated by partners.',
  'Pending Approval': 'Items awaiting an approver before they can proceed.',
  'People scored': 'People included in this scoring cycle.',
  'Pipeline Value': 'Total potential value of all open deals.',
  'Posted Entries': 'Journal entries posted to the ledger (final, not draft).',
  'Posts / period': 'Content pieces published in the selected period.',
  'Process Coverage': 'Share of business processes with a documented manual.',
  'Projected Closing': 'Forecast cash balance at period end.',
  'Promo Rate': 'Share of employees promoted in the period.',
  Promotions: 'Promotions awarded in the period.',
  Reach: 'Unique people who saw the content.',
  Recommendations: 'Open recommendations awaiting action.',
  Records: 'Total records in this dataset.',
  'Recoverable VAT': 'VAT paid on purchases that can be reclaimed from the tax authority.',
  Rejected: 'Items declined during review.',
  'Renewals (90d)': 'Contracts up for renewal in the next 90 days.',
  Requested: 'Items in the requested stage awaiting action.',
  'Resolution Rate': 'Share of tickets resolved out of all tickets opened.',
  Responded: 'Requests that received a response.',
  'Revenue (YTD)': 'Revenue recognized year-to-date.',
  Revenue: 'Total income from sales and services in the period.',
  'Reviews (H1-2026)': 'Performance reviews completed in the first half of 2026.',
  'Revision Load': 'Average revision rounds per deliverable — high values signal unclear briefs.',
  Runway: 'Months of operation left at the current burn rate.',
  'SLA Health': 'Share of service-level agreements currently being met.',
  'SLAs Tracked': 'Service-level agreements under active monitoring.',
  Sent: 'Items sent out in the period.',
  'Sessions (90d)': 'Advisory sessions held in the last 90 days.',
  Signed: 'Agreements fully signed by all parties.',
  'Sprint Velocity': 'Story points completed in the current sprint.',
  'Sprints Tracked': 'Sprints recorded for velocity tracking.',
  'Taxable Profit': 'Profit subject to corporate tax after deductions.',
  'Team Level': 'Combined XP level of the team.',
  Throughput: 'Work items completed per period.',
  'Time to Fill': 'Average days from opening a requisition to a signed offer.',
  'Total ARR': 'Total annual recurring revenue across all active contracts.',
  'Total Assets': 'Everything the company owns with monetary value.',
  'Total Breaches': 'SLA breaches recorded in the period.',
  'Total CapEx': 'Total capital expenditure — spend that creates long-lived assets.',
  'Total Channel ARR': 'Annual recurring revenue flowing through partner channels.',
  'Total Equity': 'Owners’ stake: assets minus liabilities.',
  'Total Followers': 'Combined followers across all connected platforms.',
  'Total Liabilities': 'Everything the company owes.',
  'Total OpEx': 'Total operating expenditure — the recurring cost of running the business.',
  'Total Payable': 'Total outstanding amount owed to vendors.',
  'Total Receivable': 'Total outstanding amount owed by clients.',
  'Total Rounds': 'Funding rounds raised to date.',
  'Total XP': 'Total experience points earned across activities.',
  'Trial Balance': 'Sum of all debits vs. credits — must net to zero for clean books.',
  'Upcoming Renewals': 'Contracts approaching their renewal date.',
  'Vendor Spend (yr)': 'Total spend with vendors over the year.',
  Volume: 'Total count of items in the period.',
  'Voluntary': 'Share of exits that were employee-initiated.',
  'Weighted Forecast': 'Pipeline value weighted by each deal’s probability of closing.',
  'Win Rate': 'Share of closed deals that were won.',
}

export function metricInfo(label: string): string | undefined {
  return METRIC_INFO[label]
}
