'use client'
// Barrel — public UI API. Implementation lives in the atomic-design tree
// under src/components/{atoms,molecules,organisms,templates}.
export { cn } from '@/components/atoms/cn'
export { Badge, RagBadge, HeaderBadge } from '@/components/atoms/Badge'
export { SectionTitle } from '@/components/atoms/SectionTitle'
export { Sparkline } from '@/components/atoms/Sparkline'
export { EmptyState } from '@/components/atoms/EmptyState'
export { Panel } from '@/components/molecules/Panel'
export { KpiCard } from '@/components/molecules/KpiCard'
export { ProgressBar } from '@/components/molecules/ProgressBar'
export { Fact } from '@/components/molecules/Fact'
export { Pagination } from '@/components/molecules/Pagination'
export { AreaChart } from '@/components/organisms/charts/AreaChart'
export { BarChart } from '@/components/organisms/charts/BarChart'
export { DonutChart } from '@/components/organisms/charts/DonutChart'
export { DataTable, type Column } from '@/components/organisms/DataTable'
export { PersonModal, type PersonLite } from '@/components/organisms/PersonModal'
export { PageShell } from '@/components/templates/PageShell'
export { TabBar } from '@/components/templates/TabBar'
export { Grid } from '@/components/templates/Grid'
